use dota_items;

DROP TABLE IF EXISTS items;

CREATE TABLE items (
	item_id INT PRIMARY KEY AUTO_INCREMENT,
    item_name VARCHAR(255) NOT NULL UNIQUE,
    item_description TEXT,
    item_image_path TEXT,
    item_type TEXT
);


INSERT INTO items(item_name, item_description, item_image_path, item_type)
VALUES
	("Observer Ward", "Observer Ward is an item purchasable at the Base Shop, under Consumables.", "images/Observer_Ward_icon.webp", "Consumables"),
    ("Aghanim's Shard", "Aghanim's Shard is an item purchasable at the Base Shop, under Consumables.", "images/Aghanim_Shard_icon.webp", "Consumables"),
    ("Bottle", "Bottle is an item purchasable at the Base Shop, under Consumables.","images/Bottle_29_icon.webp", "Consumables"),
    ("Town Portal Scroll", "Town Portal Scroll is an item purchasable at the Base Shop, under Consumables.","images/Town_Portal_Scroll_icon.webp", "Consumables"),
    ("Healing Salve", "Healing Salve is an item purchasable at the Base Shop, under Consumables.","images/Healing_Salve_icon.webp", "Consumables"),
    ("Tango", "Tango is an item purchasable at the Base Shop, under Consumables.","images/Tango_icon.webp", "Consumables"),
    ("Dust of Appearance", "Dust of Appearance is an item purchasable at the Base Shop, under Consumables.","images/Dust_of_Appearance_icon.webp", "Consumables"),
    ("Faerie Fire", "Faerie Fire is an item purchasable at the Base Shop, under Consumables.","images/Faerie_Fire_icon.webp", "Consumables"),
    ("Enchanted Mango", "Enchanted Mango is an item purchasable at the Base Shop, under Consumables. They may also be dug up with a Trusty Shovel icon Trusty Shovel.","images/Enchanted_Mango_icon.webp", "Consumables"),
    ("Smoke of Deceit", "Smoke of Deceit is an item purchasable at the Base Shop, under Consumables.","images/Smoke_of_Deceit_icon.webp", "Consumables"),
    ("Sentry Ward", "Sentry Ward is an item purchasable at the Base Shop, under Consumables.","images/Sentry_Ward_icon.webp", "Consumables"),
    ("Clarity", "Clarity is an item purchasable at the Base Shop, under Consumables.","images/Clarity_icon.webp", "Consumables"),
    ("Iron Branch", "Iron Branch is an item purchasable at the Base Shop, under Consumables.","images/Iron_Branch_icon.webp", "Attributes"),
    ("Blood Grenade", "Blood Grenade is an item purchasable at the Base Shop, under Consumables.","images/Blood_Grenade_icon.webp", "Consumables"),
    ("Gauntlets of Strength", "Gauntlets of Strength are an item purchasable at the Main Shop, under Attributes.","images/Gauntlets_of_Strength_icon.webp", "Attributes"),
    ("Mantle of Intelligence", "Mantle of Intelligence is an item purchasable at the Base Shop, under Attributes.","images/Mantle_of_Intelligence_icon.webp", "Attributes"),
    ("Slippers of Agility", "Slippers of Agility is an item purchasable at the Base Shop, under Attributes.","images/Slippers_of_Agility_icon.webp", "Attributes"),
    ("Circlet", "Circlet is an item purchasable at the Base Shop, under Attributes.","images/Circlet_icon.webp", "Attributes"),
    ("Band of Elvenskin", "Band of Elvenskin is an item purchasable at the Base Shop, under Attributes.","images/Band_of_Elvenskin_icon.webp", "Attributes"),
	("Belt of Strength", "Belt of Strength is an item purchasable at the Base Shop, under Attributes.","images/Belt_of_Strength_icon.webp", "Attributes"),
	("Crown", "Crown is an item purchasable at the Base Shop, under Attributes.","images/Crown_icon.webp", "Attributes"),
	("Robe of the Magi", "Robe of the Magi is an item bought at the Base Shop, under Attributes.","images/Robe_of_the_Magi_icon.webp", "Attributes"),
	("Blade of Alacrity", "Blade of Alacrity is an item purchasable at the Base Shop, under Attributes.","images/Blade_of_Alacrity_icon.webp", "Attributes"),
    ("Diadem", "Diadem is an item purchasable at the Base Shop, under Attributes.","images/Diadem_icon.webp", "Attributes"),
    ("Ogre Axe", "Ogre Axe is an item purchasable at the Base Shop, under Attributes.","images/Ogre_Axe_icon.webp", "Attributes"),
    ("Staff of Wizardry", "Staff of Wizardry is an item purchasable at the Base Shop, under Attributes.","images/Staff_of_Wizardry_icon.webp", "Attributes"),
    ("Quelling Blade", "Quelling Blade is an item purchasable at the Base Shop, under Equipment.","images/Quelling_Blade_icon.webp", "Attributes"),
    ("Infused Raindrops", "Infused Raindrops is an item purchasable at the Base Shop, under Equipment.","images/Infused_Raindrops_icon.webp", "Equipment"),
    ("Blight Stone", "Blight Stone is an item purchasable at the Main Shop, under Equipment.","images/Blight_Stone_icon.webp", "Equipment"),
    ("Gloves of Haste", "Gloves of Haste are an item purchasable at the Base Shop, under Equipment.","images/Gloves_of_Haste_icon.webp", "Equipment"),
    ("Javelin", "Javelin is an item purchasable at the Base Shop, under Equipment.","images/Javelin_icon.webp", "Equipment"),
    ("Blitz Knuckles", "Blitz Knuckles is an item purchasable at the Base Shop, under Equipment.","images/Blitz_Knuckles_icon.webp", "Equipment"),
    ("Claymore", "Claymore is an item purchasable at the Base Shop, under Equipment.","images/Claymore_icon.webp", "Equipment"),
    ("Ring of Protection", "Ring of Protection is an item purchasable at the Base Shop, under Equipment.","images/Ring_of_Protection_icon.webp", "Equipment"),
    ("Orb of Venom", "Orb of Venom is an item purchasable at the Base Shop, under Equipment.","images/Orb_of_Venom_icon.webp", "Equipment"),
    ("Blades of Attack", "Blades of Attack is an item purchasable at the Base Shop, under Equipment.","images/Blades_of_Attack_icon.webp", "Equipment"),
    ("Chainmail", "Chainmail is an item purchasable at the Base Shop, under Equipment.","images/Chainmail_icon.webp", "Equipment"),
    ("Helm of Iron Will", "Helm of Iron Will is an item purchasable at the Base Shop, under Equipment.","images/Helm_of_Iron_Will_icon.webp", "Equipment"),
    ("Broadsword", "Broadsword is an item purchasable at the Base Shop, under Equipment.","images/Broadsword_icon.webp", "Equipment"),
    ("Mithril Hammer", "Mithril Hammer is an item purchasable at the Base Shop, under Equipment.","images/Mithril_Hammer_icon.webp", "Equipment"),
    ("Ring of Regen", "Ring of Regen is an item purchasable at the Base Shop, under Miscellaneous.","images/Ring_of_Regen_icon.webp", "Miscellaneous"),
	("Magic Stick", "Magic Stick is an item purchasable at the Base Shop, under Consumables.","images/Magic_Stick_icon.webp", "Miscellaneous"),
    ("Wind Lace", "Wind Lace is an item purchasable at the Base Shop, under Miscellaneous.","images/Wind_Lace_icon.webp", "Miscellaneous"),
    ("Ring of Health", "Ring of Health is an item purchasable at the Base Shop, under Miscellaneous.","images/Ring_of_Health_icon.webp", "Miscellaneous"),
    ("Cloak", "Cloak is an item purchasable at the Base Shop, under Miscellaneous.","images/Cloak_icon.webp", "Miscellaneous"),
    ("Morbid Mask", "Morbid Mask is an item purchasable at the Base Shop, under Miscellaneous.","images/Morbid_Mask_icon.webp", "Miscellaneous"),
    ("Ghost Scepter", "Ghost Scepter is an item purchasable at the Base Shop, under Miscellaneous.","images/Ghost_Scepter_icon.webp", "Miscellaneous"),
    ("Tiara of Selemene", "The Tiara of Selemene is an item purchasable at the Secret Shop.","images/Tiara_of_Selemene_icon.webp", "Miscellaneous"),
    ("Sage's Mask", "Sage's Mask is an item purchasable at the Base Shop, under Miscellaneous.","images/Sages_Mask_icon.webp", "Miscellaneous"),
    ("Fluffy Hat", "Fluffy Hat is an item purchasable at the Base Shop, under Miscellaneous.","images/Fluffy_Hat_icon.webp", "Miscellaneous"),
    ("Boots of Speed", "Boots of Speed is an item purchasable at the Base Shop, under Miscellaneous.","images/Boots_of_Speed_icon.webp", "Miscellaneous"),
    ("Voodoo Mask", "Voodoo Mask is an item purchasable at the Base Shop, under Miscellaneous.","images/Voodoo_Mask_icon.webp", "Miscellaneous"),
    ("Gem of True Sight", "Gem of True Sight is an item purchasable at the Base Shop, under Miscellaneous.","images/Gem_of_True_Sight_icon.webp", "Miscellaneous"),
    ("Shadow Amulet", "Shadow Amulet is an item purchasable at the Base Shop, under Miscellaneous.","images/Shadow_Amulet_icon.webp", "Miscellaneous"),
    ("Ring of Tarrasque", "The Ring of Tarrasque is an item purchasable at the Secret Shop.","images/Ring_of_Tarrasque_icon.webp", "Miscellaneous"),
    ("Blink Dagger", "Blink Dagger is an item purchasable at the Base Shop, under Miscellaneous.","images/Blink_Dagger_icon.webp", "Miscellaneous"),
    ("Energy Booster", "Energy Booster is an item purchasable at the Secret Shop.","images/Energy_Booster_icon.webp", "Secret"),
    ("Cornucopia", "Cornucopia is an item purchasable at the Secret Shop.","images/Cornucopia_icon.webp", "Secret"),
    ("Talisman of Evasion", "Talisman of Evasion is an item purchasable at the Secret Shop.","images/Talisman_of_Evasion_icon.webp", "Secret"),
    ("Hyperstone", "Hyperstone is an item purchasable at the Secret Shop.","images/Hyperstone_icon.webp", "Secret"),
    ("Eaglesong", "Eaglesong is an item purchasable at the Secret Shop.","images/Eaglesong_icon.webp", "Secret"),
    ("Reaver", "Reaver is an item purchasable at the Secret Shop.","images/Reaver_icon.webp", "Secret"),
    ("Sacred Relic", "Sacred Relic is an item purchasable at the Secret Shop","images/Sacred_Relic_icon.webp", "Secret"),
    ("Vitality Booster", "Vitality Booster is an item purchasable at the Secret Shop.","images/Vitality_Booster_icon.webp", "Secret"),
    ("Point Booster", "Point Booster is an item purchasable at the Secret Shop.","images/Point_Booster_icon.webp", "Secret"),
    ("Platemail", "Platemail is an item purchasable at the Secret Shop.","images/Platemail_icon.webp", "Secret"),
    ("Demon Edge", "Demon Edge is an item purchasable at the Secret Shop.","images/Demon_Edge_icon.webp", "Secret"),
    ("Mystic Staff", "Mystic Staff is an Item purchasable at the Secret Shop.","images/Mystic_Staff_icon.webp", "Secret"),
    ("Ultimate Orb", "Ultimate Orb is an item purchasable at the Secret Shop.","images/Ultimate_Orb_icon.webp", "Secret"),
	("Magic Wand", "Observer Ward is an item purchasable at the Base Shop, under Consumables.", "images/Magic_Wand_icon.webp", "Accessories"),
    ("Null Talisman", "Null Talisman is an item purchasable at the Base Shop, under Accessories. It has 2 levels and automatically upgrades based on the in-game clock.","images/Null_Talisman_icon.webp", "Accessories"),
    ("Soul Ring", "Soul Ring is an item purchasable at the Main Shop, under Accessories.","images/Soul_Ring_icon.webp", "Accessories"),
    ("Falcon Blade", "Falcon Blade is an item purchasable at the Base Shop, under Accessories.","images/Falcon_Blade_icon.webp", "Accessories"),
    ("Power Treads", "Power Treads is an item purchasable at the Base Shop, under Accessories.","images/Power_Treads_icon.webp", "Accessories"),
    ("Oblivion Staff", "Oblivion Staff is an item purchasable at the Base Shop, under Accessories.","images/Oblivion_Staff_icon.webp", "Accessories"),
    ("Hand of Midas", "The Hand of Midas is an item purchasable at the Base Shop, under Accessories.","images/Hand_of_Midas_icon.webp", "Accessories"),
    ("Helm of the Dominator", "The Helm of the Dominator is an upgradable item purchasable at the Main Shop, under Accessories.","images/Helm_of_the_Dominator_icon.webp", "Accessories"),
    ("Helm of the Overlord", "The Helm of the Overlord is an item purchasable at the Base Shop, under Accessories.","images/Helm_of_the_Overlord_icon.webp", "Accessories"),
    ("Bracer", "Bracer is an item purchasable at the Base Shop, under Accessories. It has 2 levels and automatically upgrades based on the in-game clock.","images/Bracer_icon.webp", "Accessories"),
    ("Wraith Band", "Wraith Band is an item purchasable from the Base Shop, under Accessories. It has 2 levels and automatically upgrades based on the in-game clock.","images/Wraith_Band_icon.webp", "Accessories"),
    ("Orb of Corrosion", "Orb of Corrosion is an item purchasable at the Base Shop, under Accessories.","images/Orb_of_Corrosion_icon.webp", "Accessories"),
    ("Perseverance", "Perseverance is an item purchasable at the Base Shop, under Accessories. However, it is assembled entirely with items from the Secret Shop.","images/Perseverance_icon.webp", "Accessories"),
    ("Phase Boots", "Phase Boots is an item purchasable at the Base Shop, under Accessories.","images/Phase_Boots_icon.webp", "Accessories"),
    ("Mask of Madness", "Mask of Madness is an item purchasable at the Base Shop, under Accessories.","images/Mask_of_Madness_icon.webp", "Accessories"),
    ("Boots of Travel 1", "Boots of Travel is an item purchasable at the Base Shop, under Accessories. It can be upgraded by purchasing the recipe again.","images/Boots_of_Travel_1_icon.webp", "Accessories"),
    ("Boots of Travel 2", "Boots of Travel is an item purchasable at the Base Shop, under Accessories. ","images/Boots_of_Travel_2_icon.webp", "Accessories"),
    ("Buckler", "Buckler is an item purchasable at the Base Shop, under Support.","images/Buckler_icon.webp", "Support"),
    ("Ring of Basilius", "Ring of Basilius is an item purchasable at the Base Shop, under Support.","images/Ring_of_Basilius_(Active)_icon.webp", "Support"),
    ("Tranquil Boots", "Tranquil Boots is an item purchasable at the Base Shop, under Support.","images/Tranquil_Boots_29_icon.webp", "Support"),
    ("Pavise", "Pavise is an item purchasable at the Base Shop, under Support.","images/Pavise_icon.webp", "Support"),
    ("Mekansm", "Mekansm is an item purchasable at the Base Shop, under Support.","images/Mekansm_icon.webp", "Support"),
    ("Holy Locket", "Holy Locket is an item purchasable at the Base Shop, under Support.","images/Holy_Locket_icon.webp", "Support"),
    ("Pipe of Insight", "The Pipe of Insight is an item purchasable at the Main Shop, under Support. However, it can only be completed with items from the Secret Shop.","images/Pipe_of_Insight_icon.webp", "Support"),
    ("Guardian Greaves", "Guardian Greaves is an item purchasable at the Base Shop, under Support. However, it requires an item from the Secret Shop to be completed.","images/Guardian_Greaves_icon.webp", "Support"),
    ("Headdress", "Headdress is an item purchasable at the Base Shop, under Support.","images/Headdress_icon.webp", "Support"),
    ("Urn of Shadows", "Urn of Shadows is an item purchasable at the Base Shop, under Support.","images/Urn_of_Shadows_icon.webp", "Support"),
    ("Arcane Boots", "Arcane Boots are an item purchasable at the Base Shop, under Support.","images/Arcane_Boots_icon.webp", "Support"),
    ("Drum of Endurance", "Drum of Endurance is an item purchasable at the Base Shop, under Support.","images/Drum_of_Endurance_icon.webp", "Support"),
    ("Vladmir's Offering", "Vladmir's Offering is an item purchasable at the Base Shop, under Support.","images/Vladmirs_Offering_icon.webp", "Support"),
    ("Spirit Vessel", "Spirit Vessel is an item purchasable at the Main Shop, under Support.","images/Spirit_Vessel_icon.webp", "Support"),
    ("Boots of Bearing", "Boots of Bearing is an item purchasable at the Base Shop, under Support.","images/Boots_of_Bearing_icon.webp", "Support"),
    ("Parasma", "Parasma is an item purchasable at the Base Shop, under Weapons. However, it can only be completed with items from the Secret Shop.","images/Parasma_icon.webp", "Support"),
    ("Veil of Discord", "Veil of Discord is an item purchasable at the Base Shop, under Magical.","images/Veil_of_Discord_icon.webp", "Magical"),
    ("Force Staff", "Force Staff is an item purchasable at the Base Shop, under Magical.","images/Force_Staff_icon.webp", "Magical"),
    ("Aether Lens", "Aether Lens is an item purchasable at the Main Shop under Magical. However, it requires items from the Secret Shop to be completed.","images/Aether_Lens_icon.webp", "Magical"),
    ("Solar Crest", "Solar Crest is an item purchasable at the Base Shop, under Magical.","images/Solar_Crest_icon.webp", "Magical"),
    ("Dagon 1", "Dagon is an upgradable item purchasable at the Base Shop, under Magical.","images/Dagon_1_icon.webp", "Magical"),
    ("Dagon 2", "Dagon is an upgradable item purchasable at the Base Shop, under Magical.","images/Dagon_2_icon.webp", "Magical"),
    ("Dagon 3", "Dagon is an upgradable item purchasable at the Base Shop, under Magical.","images/Dagon_3_icon.webp", "Magical"),
    ("Dagon 4", "Dagon is an upgradable item purchasable at the Base Shop, under Magical.","images/Dagon_4_icon.webp", "Magical"),
    ("Dagon 5", "Dagon is an upgradable item purchasable at the Base Shop, under Magical.","images/Dagon_5_icon.webp", "Magical"),
    ("Aghanim's Scepter", "Aghanim's Scepter is an item purchasable at the Base Shop, under Magical. However, it requires an item from the Secret Shop to be completed.","images/Aghanims_Scepter_icon.webp", "Magical"),
    ("Refresher Orb", "Refresher Orb is an item purchasable at the Base Shop, under Magical. However, it can only be completed with items from the Secret Shop.","images/Refresher_Orb_icon.webp", "Magical"),
    ("Gleipnir", "Gleipnir is an item purchasable at the Base Shop, under Magical.","images/Gleipnir_icon.webp", "Magical"),
    ("Wind Waker", "Wind Waker is an item purchasable at the Base Shop, under Magical. However, it can only be completed with items from the Secret Shop.","images/Wind_Waker_icon.webp", "Magical"),
    ("Glimmer Cape", "Glimmer Cape is an item purchasable at the Base Shop, under Magical.","images/Glimmer_Cape_icon.webp", "Magical"),
    ("Rod of Atos", "Rod of Atos is an item purchasable at the Base Shop, under Magical.","images/Rod_of_Atos_icon.webp", "Magical"),
    ("Eul's Scepter of Divinity", "Eul's Scepter of Divinity is an item purchasable at the Base Shop, under Magical.","images/Euls_Scepter_of_Divinity_icon.webp", "Magical"),
    ("Witch Blade", "Witch Blade is an item purchasable at the Base Shop, under Magical.","images/Witch_Blade_icon.webp", "Magical"),
    ("Orchid Malevolence", "Orchid Malevolence is an item purchasable at the Base Shop, under Magical. However, it can only be completed with items from the Secret Shop.","images/Orchid_Malevolence_icon.webp", "Magical"),
    ("Octarine Core", "Octarine Core is an item listed at the Main Shop, under Magical. However, it can only be completed with items from the Secret Shop.","images/Octarine_Core_icon.webp", "Magical"),
    ("Scythe of Vyse", "Scythe of Vyse is an item purchasable at the Base Shop, under Magical. However, it is assembled entirely with items from the Secret Shop.","images/Scythe_of_Vyse_icon.webp", "Magical"),
    ("Aghanim's Blessing", "Aghanim's Blessing is an item purchasable at the Base Shop, under Magical.","images/Aghanims_Blessing_icon.webp", "Magical"),
    ("Vanguard", "Vanguard is an item purchasable at the Base Shop, under Armor. However, it requires an item from the Secret Shop to be completed.","images/Vanguard_icon.webp", "Armor"),
    ("Aeon Disk", "Aeon Disk is an item purchasable at the Main Shop, under Armor. However, it can only be completed with items from the Secret Shop.","images/Aeon_Disk_icon.webp", "Armor"),
    ("Eternal Shroud", "Eternal Shroud is an item purchasable at the Base Shop, under Armor. However, it can only be completed with items from the Secret Shop.","images/Eternal_Shroud_icon.webp", "Armor"),
    ("Lotus Orb", "The Lotus Orb is an item purchasable at the Main Shop, under Armor. However, it requires items from the Secret Shop to be assembled, or can be assembled entirely with items from the Secret Shop.","images/Lotus_Orb_icon.webp", "Armor"),
    ("Bloodstone", "The Bloodstone is an item listed at the Base Shop, under Armor. However, it requires items from the Secret Shop to be assembled.","images/Bloodstone_icon.webp", "Armor"),
    ("Manta Style", "Manta Style is an item purchasable at the Main Shop, under Armor.","images/Manta_Style_icon.webp", "Armor"),
    ("Shiva's Guard", "Shiva's Guard is an item purchasable at the Base Shop, under Armor. However, it can only be completed with items from the Secret Shop.","images/Shivas_Guard_icon.webp", "Armor"),
    ("Heart of Tarrasque", "Heart of Tarrasque is an item listed at the Main Shop, under Armor. However, it can only be completed with items from the Secret Shop.","images/Heart_of_Tarrasque_icon.webp", "Armor"),
    ("Blade Mail", "Blade Mail is an item purchasable at the Base Shop, under Armor.","images/Blade_Mail_icon.webp", "Armor"),
    ("Soul Booster", "Soul Booster is an item listed at the Base Shop, under Armor. However, it is assembled entirely with items from the Secret Shop.","images/Soul_Booster_icon.webp", "Armor"),
    ("Crimson Guard", "Crimson Guard is an item listed under the Base Shop under Armor. However, it requires an item from the Secret Shop to be completed.","images/Crimson_Guard_icon.webp", "Armor"),
    ("Black King Bar", "Black King Bar is an item purchasable at the Base Shop, under Armor.","images/Black_King_Bar_icon.webp", "Armor"),
    ("Hurricane Pike", "Hurricane Pike is an item purchasable at the Base Shop, under Armor.","images/Hurricane_Pike_icon.webp", "Armor"),
    ("Linken's Sphere", "Linken's Sphere is an item purchasable at the Main Shop, under Armor. However, it can only be completed with items from the Secret Shop.","images/Linkens_Sphere_icon.webp", "Armor"),
    ("Assault Cuirass", "The Assault Cuirass is an item purchasable at the Base Shop, under Armor. However, it can only be completed with items from the Secret Shop.","images/Assault_Cuirass_icon.webp", "Armor"),
    ("Crystalys", "Crystalys is an item purchasable at the Base Shop, under Weapons.","images/Crystalys_icon.webp", "Weapons"),
    ("Skull Basher", "Skull Basher is an item purchasable at the Base Shop, under Weapons.","images/Skull_Basher_icon.webp", "Weapons"),
    ("Meteor Hammer", "Meteor Hammer is an item purchasable at the Base Shop, under Weapons. However, it requires an item from the Secret Shop to be completed.","images/Meteor_Hammer_icon.webp", "Weapons"),
    ("Battle Fury", "Battle Fury is an item purchasable at the Base Shop, under Weapons. However, it requires items from the Secret Shop to be completed.","images/Battle_Fury_icon.webp", "Weapons"),
    ("Radiance", "Radiance is an item purchasable at the Base Shop, under Weapons. However, it can only be completed with items from the Secret Shop.","images/Radiance_29_icon.webp", "Weapons"),
    ("Revenant's Brooch", "Revenant's Brooch is an item purchasable at the Base Shop, under Weapons. However, it can only be completed with items from the Secret Shop.","images/Revenants_Brooch_icon.webp", "Weapons"),
    ("Daedalus", "Daedalus is an item purchasable at the Base Shop, under Weapons. However, it can only be completed with items from the Secret Shop.","images/Daedalus_icon.webp", "Weapons"),
    ("Butterfly", "Butterfly is an item purchasable at the Main Shop, under Weapons. However, it can only be completed with items from the Secret Shop.","images/Butterfly_icon.webp", "Weapons"),
    ("Divine Rapier", "Divine Rapier is an item listed at the Base Shop, under Weapons. However, it is assembled entirely with items from the Secret Shop.","images/Divine_Rapier_icon.webp", "Weapons"),
    ("Abyssal Blade", "Abyssal Blade is an item purchasable at the Main Shop under Weapons. However, it can only be completed with items from the Secret Shop.","images/Abyssal_Blade_icon.webp", "Weapons"),
    ("Armlet of Mordiggian", "Armlet of Mordiggian is an item purchasable at the Base Shop, under Weapons.","images/Armlet_of_Mordiggian_29_icon.webp", "Weapons"),
    ("Shadow Blade", "Shadow Blade is an item purchasable at the Main Shop, under Weapons.","images/Shadow_Blade_icon.webp", "Weapons"),
    ("Desolator", "Desolator is an item purchasable at the Base Shop, under Weapons.","images/Desolator_icon.webp", "Weapons"),
    ("Nullifier", "Nullifier is an item purchasable at the Base Shop, under Weapons. However, it requires an item from the Secret Shop to be completed.","images/Nullifier_icon.webp", "Weapons"),
    ("Monkey King Bar", "Monkey King Bar is an item purchasable at the Main Shop, under Weapons. However, it can only be completed with items from the Secret Shop.","images/Monkey_King_Bar_icon.webp", "Weapons"),
    ("Khanda", "Khanda is an item purchasable at the Base Shop, under Weapons. However, it can only be completed with items from the Secret Shop.","images/Khanda_icon.webp", "Weapons"),
    ("Ethereal Blade", "Ethereal Blade is an item purchasable at the Base Shop, under Weapons.","images/Ethereal_Blade_icon.webp", "Weapons"),
    ("Silver Edge", "Silver Edge is an item purchasable at the Base Shop, under Weapons.","images/Silver_Edge_icon.webp", "Weapons"),
    ("Disperser", "Disperser is an item purchasable at the Base Shop, under Weapons.","images/Disperser_icon.webp", "Weapons"),
    ("Bloodthorn", "Bloodthorn is an item purchasable at the Base Shop, under Weapons. However, it requires an item from the Secret Shop to be completed.","images/Bloodthorn_icon.webp", "Weapons"),
    ("Dragon Lance", "Dragon Lance is an item purchasable at the Base Shop, under Artifacts.","images/Dragon_Lance_icon.webp", "Artifacts"),
    ("Sange", "Sange is an item purchasable at the Base Shop, under Artifacts.","images/Sange_icon.webp", "Artifacts"),
    ("Phylactery", "Phylactery is an item purchasable at the Base Shop, under Artifacts.","images/Phylactery_icon.webp", "Artifacts"),
    ("Mage Slayer", "Mage Slayer is an item purchasable at the Base Shop, under Artifacts.","images/Mage_Slayer_icon.webp", "Artifacts"),
    ("Maelstrom", "Maelstrom is an item purchasable at the Main Shop, under Artifacts.","images/Maelstrom_icon.webp", "Artifacts"),
    ("Kaya and Sange", "Kaya and Sange is an item purchasable at the Base Shop, under Artifacts.","images/Kaya_and_Sange_icon.webp", "Artifacts"),
    ("Yasha and Kaya", "Yasha and Kaya is an item purchasable at the Base Shop, under Artifacts.","images/Yasha_and_Kaya_icon.webp", "Artifacts"),
    ("Satanic", "Satanic is an item purchasable at the Base Shop, under Artifacts. However, it can only be completed with items from the Secret Shop.","images/Satanic_icon.webp", "Artifacts"),
    ("Mjollnir", "Mjollnir is an item purchasable at the Base Shop, under Artifacts. However, it can only be completed with items from the Secret Shop.","images/Mjollnir_icon.webp", "Artifacts"),
    ("Overwhelming Blink", "Overwhelming Blink is an item purchasable at the Base Shop, under Arcane. However, it can only be completed with items from the Secret Shop.","images/Overwhelming_Blink_icon.webp", "Artifacts"),
    ("Kaya", "Kaya is an item purchasable at the Base Shop, under Artifacts.","images/Kaya_icon.webp", "Artifacts"),
    ("Yasha", "Yasha is an Item purchasable at the Base Shop, under Artifacts.","images/Yasha_icon.webp", "Artifacts"),
    ("Diffusal Blade", "Diffusal Blade is an item purchasable at the Base Shop, under Artifacts.","images/Diffusal_Blade_1_icon.webp", "Artifacts"),
    ("Echo Sabre", "Echo Sabre is an item purchasable at the Base Shop, under Artifacts.","images/Echo_Sabre_icon.webp", "Artifacts"),
    ("Heaven's Halberd", "Heaven's Halberd is an item purchasable at the Main Shop, under Artifacts. However, it requires an item from the Secret Shop to be completed.","images/Heavens_Halberd_icon.webp", "Artifacts"),
    ("Sange and Yasha", "Sange and Yasha is an item purchasable at the Base Shop, under Artifacts.","images/Sange_and_Yasha_icon.webp", "Artifacts"),
    ("Harpoon", "Harpoon is an item purchasable at the Base Shop, under Artifacts.","images/Harpoon_icon.webp", "Artifacts"),
    ("Eye of Skadi", "Eye of Skadi is an item purchasable at the Main Shop, under Artifacts. However, it is assembled entirely with items from the Secret Shop.","images/Eye_of_Skadi_icon.webp", "Artifacts"),
    ("Arcane Blink", "Arcane Blink is an item purchasable at the Base Shop, under Arcane. However, it can only be completed with items from the Secret Shop.","images/Arcane_Blink_icon.webp", "Artifacts"),
    ("Swift Blink", "Swift Blink is an item purchasable at the Main Shop, under Arcane. However, it can only be completed with items from the Secret Shop.","images/Swift_Blink_icon.webp", "Artifacts"),
    ("Aegis of the Immortal", "The Aegis of the Immortal is a Kill Reward item dropped by Roshan icon Roshan on his first death and onwards.","images/Aegis_of_the_Immortal_icon.webp", "Roshan"),
    ("Aghanim's Shard - Roshan", "Aghanim's Shard - Roshan is a Kill Reward item granted by Tormentors when defeated.","images/Aghanims_Shard_Roshan_icon.webp", "Roshan"),
    ("Refresher Shard", "Refresher Shard is a Kill Reward item which can be dropped by Roshan on his third death onwards.","images/Refresher_Shard_icon.webp", "Roshan"),
    ("Aghanim's Blessing - Roshan", "Aghanim's Blessing - Roshan is a Kill Reward item which can be dropped by Roshan on his third death onwards.","images/Aghanims_Blessing_Roshan_icon.webp", "Roshan"),
    ("Cheese", "Cheese is a consumable Kill Reward item that can be dropped by Roshan on his second death and onwards.","images/Cheese_icon.webp", "Roshan"),
    ("Roshan's Banner", "Roshan's Banner is a Kill Reward item which can be dropped by Roshan on his second death onwards.","images/Roshans_Banner_icon.webp", "Roshan"),
	("Magic Wand recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Magic_Wand_recipe_icon.webp", "Recipe"),
    ("Null Talisman recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Null_Talisman_recipe_icon.webp", "Recipe"),
    ("Soul Ring recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Soul_Ring_recipe_icon.webp", "Recipe"),
	("Falcon Blade recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Falcon_Blade_recipe_icon.webp", "Recipe"),
    ("Power Treads Strength", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Power_Treads_str_icon.webp", "Recipe"),
    ("Power Treads Agility", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Power_Treads_agi_icon.webp", "Recipe"),
    ("Power Treads Intelligence", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Power_Treads_int_icon.webp", "Recipe"),
    ("Hand of Midas recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Hand_of_Midas_recipe_icon.webp", "Recipe"),
	("Helm of the Overlord recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Default_recipe_icon.webp", "Recipe"),
    ("Bracer recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Bracer_recipe_icon.webp", "Recipe"),
    ("Wraith Band recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Wraith_Band_recipe_icon.webp", "Recipe"),
    ("Buckler recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Buckler_recipe_icon.webp", "Recipe"),
	("Ring of Basilius recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Ring_of_Basilius_recipe_icon.webp", "Recipe"),
    ("Pavise recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Default_recipe_icon.webp", "Recipe"),
    ("Mekansm recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Mekansm_recipe_icon.webp", "Recipe"),
    ("Pipe of Insight recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Pipe_of_Insight_recipe_icon.webp", "Recipe"),
    ("Guardian Greaves recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Guardian_Greaves_recipe_icon.webp", "Recipe"),
    ("Headdress recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Headdress_recipe_icon.webp", "Recipe"),
    ("Urn of Shadows recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Urn_of_Shadows_recipe_icon.webp", "Recipe"),
    ("Arcane Boots recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Default_recipe_icon.webp", "Recipe"),
    ("Drum of Endurance recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Drum_of_Endurance_recipe_icon.webp", "Recipe"),
    ("Spirit Vessel recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Spirit_Vessel_recipe_icon.webp", "Recipe"),
    ("Boots of Bearing recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Boots_of_Bearing_recipe_icon.webp", "Recipe"),
    ("Veil of Discord recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Veil_of_Discord_recipe_icon.webp", "Recipe"),
    ("Force Staff recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Force_Staff_recipe_icon.webp", "Recipe"),
    ("Aether Lens recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Aether_Lens_recipe_icon.webp", "Recipe"),
    ("Solar Crest recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Solar_Crest_recipe_icon.webp", "Recipe"),
    ("Dagon recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Dagon_recipe_icon.webp", "Recipe"),
    ("Refresher Orb recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Refresher_Orb_recipe_icon.webp", "Recipe"),
    ("Gleipnir recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Gleipnir_recipe_icon.webp", "Recipe"),
    ("Wind Waker recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Wind_Waker_recipe_icon.webp", "Recipe"),
    ("Glimmer Cape recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Glimmer_Cape_recipe_icon.webp", "Recipe"),
    ("Eul's Scepter of Divinity recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Euls_Scepter_of_Divinity_recipe_icon.webp", "Recipe"),
    ("Witch Blade recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Witch_Blade_recipe_icon.webp", "Recipe"),
    ("Orchid Malevolence recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Orchid_Malevolence_recipe_icon.webp", "Recipe"),
    ("Scythe of Vyse recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Default_recipe_icon.webp", "Recipe"),
    ("Aghanim's Blessing recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Aghanims_Blessing_recipe_icon.webp", "Recipe"),
    ("Aeon Disk recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Aeon_Disk_recipe_icon.webp", "Recipe"),
    ("Eternal Shroud recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Eternal_Shroud_recipe_icon.webp", "Recipe"),
    ("Lotus Orb recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Default_recipe_icon.webp", "Recipe"),
    ("Bloodstone recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Bloodstone_recipe_icon.webp", "Recipe"),
    ("Manta Style recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Manta_Style_recipe_icon.webp", "Recipe"),
    ("Shiva's Guard recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Shivas_Guard_recipe_icon.webp", "Recipe"),
    ("Heart of Tarrasque recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Heart_of_Tarrasque_recipe_icon.webp", "Recipe"),
    ("Blade Mail recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Blade_Mail_recipe_icon.webp", "Recipe"),
    ("Crimson Guard recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Crimson_Guard_recipe_icon.webp", "Recipe"),
    ("Black King Bar recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Black_King_Bar_recipe_icon.webp", "Recipe"),
    ("Hurricane Pike recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Hurricane_Pike_recipe_icon.webp", "Recipe"),
    ("Linkens Sphere recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Linkens_Sphere_recipe_icon.webp", "Recipe"),
    ("Assault Cuirass recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Assault_Cuirass_recipe_icon.webp", "Recipe"),
    ("Crystalys recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Crystalys_recipe_icon.webp", "Recipe"),
    ("Skull Basher recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Skull_Basher_recipe_icon.webp", "Recipe"),
    ("Meteor Hammer recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Meteor_Hammer_recipe_icon.webp", "Recipe"),
    ("Battle Fury recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Battle_Fury_recipe_icon.webp", "Recipe"),
    ("Revenant's Brooch recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Revenants_Brooch_recipe_icon.webp", "Recipe"),
    ("Daedalus recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Daedalus_recipe_icon.webp", "Recipe"),
    ("Abyssal Blade recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Abyssal_Blade_recipe_icon.webp", "Recipe"),
    ("Armlet of Mordiggian recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Armlet_of_Mordiggian_recipe_icon.webp", "Recipe"),
    ("Monkey King Bar recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Monkey_King_Bar_recipe_icon.webp", "Recipe"),
    ("Khanda recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Default_recipe_icon.webp", "Recipe"),
    ("Ethereal Blade recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Ethereal_Blade_recipe_icon.webp", "Recipe"),
    ("Silver Edge recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Silver_Edge_recipe_icon.webp", "Recipe"),
    ("Disperser recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Default_recipe_icon.webp", "Recipe"),
    ("Bloodthorn recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Bloodthorn_recipe_icon.webp", "Recipe"),
    ("Dragon Lance recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Default_recipe_icon.webp", "Recipe"),
    ("Sange recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Sange_recipe_icon.webp", "Recipe"),
    ("Phylactery recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Default_recipe_icon.webp", "Recipe"),
    ("Mage Slayer recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Mage_Slayer_recipe_icon.webp", "Recipe"),
    ("Mjollnir recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Mjollnir_recipe_icon.webp", "Recipe"),
    ("Overwhelming Blink recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Overwhelming_Blink_recipe_icon.webp", "Recipe"),
    ("Kaya recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Kaya_recipe_icon.webp", "Recipe"),
    ("Yasha recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Yasha_recipe_icon.webp", "Recipe"),
    ("Diffusal Blade recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Diffusal_Blade_recipe_icon.webp", "Recipe"),
    ("Heaven's Halberd recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Heavens_Halberd_recipe_icon.webp", "Recipe"),
    ("Harpoon recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Default_recipe_icon.webp", "Recipe"),
    ("Eye of Skadi recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Default_recipe_icon.webp", "Recipe"),
    ("Arcane Blink recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Arcane_Blink_recipe_icon.webp", "Recipe"),
    ("Swift Blink recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Swift_Blink_recipe_icon.webp", "Recipe"),
    ("Holy Locket recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Holy_Locket_recipe_icon.webp", "Recipe"),
    ("Helm of the Dominator recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Helm_of_the_Dominator_recipe_icon.webp", "Recipe"),
	("Boots of Travel recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Boots_of_Travel_recipe_icon.webp", "Recipe"),
    ("Moon Shard", "Moon Shard is an item listed at the Base Shop, under Accessories. However, it is assembled entirely with items from the Secret Shop.","images/Moon_Shard_icon.webp", "Recipe"),
    ("Rod of Atos recipe", "A recipe is an item that does nothing on its own, but when combined with the right ingredients allows heroes to create more powerful items.","images/Rod_of_Atos_recipe_icon.webp", "Recipe");